apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        name: db-deployment
        app: voting-app
    spec:
      containers:
      - name: postgres-db
        image: postgres:9.4
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}