apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: redis
  labels:
    name: redis-service
spec:
  selector:
    name: redis-deployment
    app: voting-app
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379