apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: vote-deployment
  labels:
    name: voting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        name: voting-deployment
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:before
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"